namespace Scruffy.ServiceHosts.DpsReportAnalyzer.Data.Report
{
    /// <summary>
    /// Target buff item
    /// </summary>
    public class JsonBuffsUptimeData
    {
        /// <summary>
        /// Uptime of the buff
        /// </summary>
        public double Uptime { get; set; }

        /// <summary>
        /// Presence of the buff (intensity only)
        /// </summary>
        public double Presence { get; set; }

        /// <summary>
        /// Buff generated by
        /// </summary>
        public IReadOnlyDictionary<string, double> Generated { get; set; }

        /// <summary>
        /// Buff overstacked by
        /// </summary>
        public IReadOnlyDictionary<string, double> Overstacked { get; set; }

        /// <summary>
        /// Buff wasted by
        /// </summary>
        public IReadOnlyDictionary<string, double> Wasted { get; set; }

        /// <summary>
        /// Buff extended by unknown for
        /// </summary>
        public IReadOnlyDictionary<string, double> UnknownExtended { get; set; }

        /// <summary>
        /// Buff by extension
        /// </summary>
        public IReadOnlyDictionary<string, double> ByExtension { get; set; }

        /// <summary>
        /// Buff extended for
        /// </summary>
        public IReadOnlyDictionary<string, double> Extended { get; set; }
    }
}