// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Scruffy.Data.Entity;

namespace Scruffy.Data.Entity.Migrations
{
    [DbContext(typeof(ScruffyDbContext))]
    [Migration("20210807133807_Update22")]
    partial class Update22
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Account.AccountEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(42)
                        .HasColumnType("nvarchar(42)");

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DpsReportUserToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Name");

                    b.HasIndex("UserId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("CalendarAppointmentScheduleId")
                        .HasColumnType("bigint");

                    b.Property<long>("CalendarAppointmentTemplateId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("ReminderChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("ReminderMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CalendarAppointmentScheduleId");

                    b.HasIndex("CalendarAppointmentTemplateId");

                    b.ToTable("CalendarAppointments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentParticipantEntity", b =>
                {
                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit");

                    b.HasKey("AppointmentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("CalendarAppointmentParticipants");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentScheduleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AdditionalData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CalendarAppointmentTemplateId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ServerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CalendarAppointmentTemplateId");

                    b.ToTable("CalendarAppointmentSchedules");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentTemplateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GuildPoints")
                        .HasColumnType("float");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRaisingGuildPointCap")
                        .HasColumnType("bit");

                    b.Property<string>("ReminderMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("ReminderTime")
                        .HasColumnType("time");

                    b.Property<decimal>("ServerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Uri")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServerId");

                    b.ToTable("CalendarAppointmentTemplates");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.CoreData.ServerConfigurationEntity", b =>
                {
                    b.Property<decimal>("ServerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<decimal?>("AdministratorRoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServerId");

                    b.ToTable("ServerConfigurations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.CoreData.UserEntity", b =>
                {
                    b.Property<decimal>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<DateTime>("CreationTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RaidExperienceLevelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RaidExperienceLevelId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Fractals.FractalAppointmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AppointmentTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("FractalAppointments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Fractals.FractalLfgConfigurationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FractalLfgConfigurations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Fractals.FractalRegistrationEntity", b =>
                {
                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AppointmentTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long?>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationTimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ConfigurationId", "AppointmentTimeStamp", "UserId");

                    b.HasIndex("AppointmentId");

                    b.ToTable("FractalRegistrations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.General.LogEntryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualifiedCommandName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogEntries");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.GuildAdministration.GuildEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApiKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalendarDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CalendarTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordServerId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("GuildCalendarChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("GuildCalendarMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<string>("GuildId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MessageOfTheDayChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("MessageOfTheDayMessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("NotificationChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("ReminderChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("DiscordServerId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.GuildAdministration.GuildLogEntryEntity", b =>
                {
                    b.Property<long>("GuildId")
                        .HasColumnType("bigint");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Activity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Coins")
                        .HasColumnType("int");

                    b.Property<int?>("Count")
                        .HasColumnType("int");

                    b.Property<string>("InvitedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("KickedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageOfTheDay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldRank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Participants")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TotalParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UpgradeId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GuildId", "Id");

                    b.ToTable("GuildLogEntries");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidAppointmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ConfigurationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCommitted")
                        .HasColumnType("bit");

                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("TemplateId");

                    b.ToTable("RaidAppointments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidCurrentUserPointsEntity", b =>
                {
                    b.Property<decimal>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(20,0)")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<double>("Points")
                        .HasColumnType("float");

                    b.Property<decimal?>("UserId1")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("RaidCurrentUserPoints");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidDayConfigurationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<decimal>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<TimeSpan>("RegistrationDeadline")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("RaidDayConfigurations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidDayTemplateEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RaidDayTemplates");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidExperienceAssignmentEntity", b =>
                {
                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExperienceLevelId")
                        .HasColumnType("bigint");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.HasKey("TemplateId", "ExperienceLevelId");

                    b.HasIndex("ExperienceLevelId");

                    b.ToTable("RaidExperienceAssignments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AliasName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordEmoji")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal?>("DiscordRoleId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("ParticipationPoints")
                        .HasColumnType("bigint");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<long?>("SuperiorExperienceLevelId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SuperiorExperienceLevelId");

                    b.ToTable("RaidExperienceLevels");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRegistrationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AppointmentId")
                        .HasColumnType("bigint");

                    b.Property<long?>("LineupExperienceLevelId")
                        .HasColumnType("bigint");

                    b.Property<long?>("Points")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("RegistrationTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("LineupExperienceLevelId");

                    b.HasIndex("UserId");

                    b.ToTable("RaidRegistrations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRegistrationRoleAssignmentEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("MainRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("RegistrationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MainRoleId");

                    b.HasIndex("RegistrationId");

                    b.HasIndex("SubRoleId");

                    b.ToTable("RaidRegistrationRoleAssignments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRequiredRoleEntity", b =>
                {
                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("Index")
                        .HasColumnType("bigint");

                    b.Property<long>("MainRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("TemplateId", "Index");

                    b.HasIndex("MainRoleId");

                    b.HasIndex("SubRoleId");

                    b.ToTable("RaidRequiredRoles");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleAliasNameEntity", b =>
                {
                    b.Property<string>("AliasName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("MainRoleId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SubRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("AliasName");

                    b.HasIndex("MainRoleId");

                    b.HasIndex("SubRoleId");

                    b.ToTable("RaidRoleAliasNames");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscordEmojiId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long?>("MainRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MainRoleId");

                    b.ToTable("RaidRoles");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupAssignmentEntity", b =>
                {
                    b.Property<long>("TemplateId")
                        .HasColumnType("bigint");

                    b.Property<long>("LineupHeaderId")
                        .HasColumnType("bigint");

                    b.HasKey("TemplateId", "LineupHeaderId");

                    b.HasIndex("LineupHeaderId");

                    b.ToTable("RaidRoleLineupAssignments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupEntryEntity", b =>
                {
                    b.Property<long>("LineupHeaderId")
                        .HasColumnType("bigint");

                    b.Property<long>("Position")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("LineupHeaderId", "Position", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("RaidRoleLineupEntries");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupHeaderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RaidRoleLineupHeaders");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidUserRoleEntity", b =>
                {
                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<long>("MainRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("SubRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("UserId", "MainRoleId", "SubRoleId");

                    b.HasIndex("MainRoleId");

                    b.HasIndex("SubRoleId");

                    b.ToTable("RaidUserRoles");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Reminder.OneTimeReminderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<bool>("IsExecuted")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("UserId")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OneTimeReminders");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Reminder.WeeklyReminderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("DeletionTime")
                        .HasColumnType("time");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MessageId")
                        .HasColumnType("decimal(20,0)");

                    b.Property<TimeSpan>("PostTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("WeeklyReminders");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Account.AccountEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.UserEntity", "User")
                        .WithMany("Accounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentScheduleEntity", "CalendarAppointmentSchedule")
                        .WithMany()
                        .HasForeignKey("CalendarAppointmentScheduleId");

                    b.HasOne("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentTemplateEntity", "CalendarAppointmentTemplate")
                        .WithMany("CalendarAppointments")
                        .HasForeignKey("CalendarAppointmentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarAppointmentSchedule");

                    b.Navigation("CalendarAppointmentTemplate");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentParticipantEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentEntity", "CalendarAppointment")
                        .WithMany("CalendarAppointmentParticipants")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarAppointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentScheduleEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentTemplateEntity", "CalendarAppointmentTemplate")
                        .WithMany("CalendarAppointmentSchedules")
                        .HasForeignKey("CalendarAppointmentTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalendarAppointmentTemplate");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentTemplateEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.ServerConfigurationEntity", "ServerConfiguration")
                        .WithMany()
                        .HasForeignKey("ServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServerConfiguration");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.CoreData.UserEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", "RaidExperienceLevel")
                        .WithMany("Users")
                        .HasForeignKey("RaidExperienceLevelId");

                    b.Navigation("RaidExperienceLevel");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Fractals.FractalAppointmentEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Fractals.FractalLfgConfigurationEntity", "FractalLfgConfiguration")
                        .WithMany()
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FractalLfgConfiguration");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Fractals.FractalRegistrationEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Fractals.FractalAppointmentEntity", "FractalAppointmentEntity")
                        .WithMany()
                        .HasForeignKey("AppointmentId");

                    b.HasOne("Scruffy.Data.Entity.Tables.Fractals.FractalLfgConfigurationEntity", "FractalLfgConfiguration")
                        .WithMany("FractalRegistrations")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FractalAppointmentEntity");

                    b.Navigation("FractalLfgConfiguration");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.GuildAdministration.GuildEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.ServerConfigurationEntity", "ServerConfiguration")
                        .WithMany()
                        .HasForeignKey("DiscordServerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServerConfiguration");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.GuildAdministration.GuildLogEntryEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.GuildAdministration.GuildEntity", "Guild")
                        .WithMany("GuildLogEntries")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Guild");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidAppointmentEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidDayConfigurationEntity", "RaidDayConfiguration")
                        .WithMany("RaidAppointments")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidDayTemplateEntity", "RaidDayTemplate")
                        .WithMany("RaidAppointments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaidDayConfiguration");

                    b.Navigation("RaidDayTemplate");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidCurrentUserPointsEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId1");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidExperienceAssignmentEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", "RaidExperienceLevel")
                        .WithMany("RaidExperienceAssignments")
                        .HasForeignKey("ExperienceLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidDayTemplateEntity", "RaidDayTemplate")
                        .WithMany("RaidExperienceAssignments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaidDayTemplate");

                    b.Navigation("RaidExperienceLevel");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", "SuperiorRaidExperienceLevel")
                        .WithMany("InferiorRaidExperienceLevels")
                        .HasForeignKey("SuperiorExperienceLevelId");

                    b.Navigation("SuperiorRaidExperienceLevel");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRegistrationEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidAppointmentEntity", "RaidAppointment")
                        .WithMany("RaidRegistrations")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", "LineupExperienceLevel")
                        .WithMany()
                        .HasForeignKey("LineupExperienceLevelId");

                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.UserEntity", "User")
                        .WithMany("RaidRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LineupExperienceLevel");

                    b.Navigation("RaidAppointment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRegistrationRoleAssignmentEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "MainRaidRole")
                        .WithMany()
                        .HasForeignKey("MainRoleId");

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRegistrationEntity", "RaidRegistration")
                        .WithMany("RaidRegistrationRoleAssignments")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "SubRaidRole")
                        .WithMany()
                        .HasForeignKey("SubRoleId");

                    b.Navigation("MainRaidRole");

                    b.Navigation("RaidRegistration");

                    b.Navigation("SubRaidRole");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRequiredRoleEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "MainRaidRole")
                        .WithMany()
                        .HasForeignKey("MainRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "SubRaidRole")
                        .WithMany()
                        .HasForeignKey("SubRoleId");

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidDayTemplateEntity", "RaidDayTemplateEntity")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainRaidRole");

                    b.Navigation("RaidDayTemplateEntity");

                    b.Navigation("SubRaidRole");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleAliasNameEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "MainRaidRole")
                        .WithMany()
                        .HasForeignKey("MainRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "SubRaidRole")
                        .WithMany()
                        .HasForeignKey("SubRoleId");

                    b.Navigation("MainRaidRole");

                    b.Navigation("SubRaidRole");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "MainRaidRole")
                        .WithMany("SubRaidRoles")
                        .HasForeignKey("MainRoleId");

                    b.Navigation("MainRaidRole");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupAssignmentEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupHeaderEntity", "RaidRoleLineupHeader")
                        .WithMany("RaidRoleLineupAssignments")
                        .HasForeignKey("LineupHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidDayTemplateEntity", "RaidDayTemplate")
                        .WithMany("RaidRoleLineupAssignments")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaidDayTemplate");

                    b.Navigation("RaidRoleLineupHeader");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupEntryEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupHeaderEntity", "RaidRoleLineupHeader")
                        .WithMany("RaidRoleLineupEntries")
                        .HasForeignKey("LineupHeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "RaidRole")
                        .WithMany("RaidRoleLineupEntries")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RaidRole");

                    b.Navigation("RaidRoleLineupHeader");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidUserRoleEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "MainRaidRole")
                        .WithMany()
                        .HasForeignKey("MainRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", "SubRaidRole")
                        .WithMany()
                        .HasForeignKey("SubRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.UserEntity", "User")
                        .WithMany("RaidUserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MainRaidRole");

                    b.Navigation("SubRaidRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Reminder.OneTimeReminderEntity", b =>
                {
                    b.HasOne("Scruffy.Data.Entity.Tables.CoreData.UserEntity", "User")
                        .WithMany("OneTimeReminders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentEntity", b =>
                {
                    b.Navigation("CalendarAppointmentParticipants");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Calendar.CalendarAppointmentTemplateEntity", b =>
                {
                    b.Navigation("CalendarAppointments");

                    b.Navigation("CalendarAppointmentSchedules");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.CoreData.UserEntity", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("OneTimeReminders");

                    b.Navigation("RaidRegistrations");

                    b.Navigation("RaidUserRoles");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Fractals.FractalLfgConfigurationEntity", b =>
                {
                    b.Navigation("FractalRegistrations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.GuildAdministration.GuildEntity", b =>
                {
                    b.Navigation("GuildLogEntries");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidAppointmentEntity", b =>
                {
                    b.Navigation("RaidRegistrations");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidDayConfigurationEntity", b =>
                {
                    b.Navigation("RaidAppointments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidDayTemplateEntity", b =>
                {
                    b.Navigation("RaidAppointments");

                    b.Navigation("RaidExperienceAssignments");

                    b.Navigation("RaidRoleLineupAssignments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidExperienceLevelEntity", b =>
                {
                    b.Navigation("InferiorRaidExperienceLevels");

                    b.Navigation("RaidExperienceAssignments");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRegistrationEntity", b =>
                {
                    b.Navigation("RaidRegistrationRoleAssignments");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleEntity", b =>
                {
                    b.Navigation("RaidRoleLineupEntries");

                    b.Navigation("SubRaidRoles");
                });

            modelBuilder.Entity("Scruffy.Data.Entity.Tables.Raid.RaidRoleLineupHeaderEntity", b =>
                {
                    b.Navigation("RaidRoleLineupAssignments");

                    b.Navigation("RaidRoleLineupEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
