using System.Collections.Generic;

namespace Scruffy.WebApp.Components.Pages.DpsReports.Data;

/// <summary>
/// Personal statistics
/// </summary>
public class PersonalStatistics
{
    /// <summary>
    /// Character name of the own player in this encounter
    /// </summary>
    public string PlayerCharacterName { get; set; }

    /// <summary>
    /// Player role
    /// </summary>
    public string PlayerRole { get; set; }

    /// <summary>
    /// The average alacrity uptime generated by the player during the encounter
    /// </summary>
    public double? Alacrity { get; set; }

    /// <summary>
    /// The average quickness uptime generated by the player during the encounter
    /// </summary>
    public double? Quickness { get; set; }

    /// <summary>
    /// Player DPS
    /// </summary>
    public int? PlayerDps { get; set; }

    /// <summary>
    /// Mechanics data for the own player
    /// </summary>
    public List<Mechanic> Mechanics { get; set; } = [];
}